# Generated by Django 3.2.7 on 2021-09-03 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_user_category_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='expense',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.category'),
        ),
    ]
